/**
 * Copyright (c) 2026 OpenBKN
 * SPDX-License-Identifier: LicenseRef-OpenBKN
 */

import { PlusOutlined, ReloadOutlined } from "@ant-design/icons";
import { Alert, Checkbox, Descriptions, Drawer, Form, InputNumber, Modal, Select, Space, Tag } from "antd";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";

import { useAppServices } from "@/framework/context/use-app-services";
import { PermissionGate } from "@/framework/permission/PermissionGate";
import { extractRequestErrorMessage } from "@/framework/request/error-message";
import { AppButton } from "@/framework/ui/common/AppButton";
import { AppTable } from "@/framework/ui/common/AppTable";
import { EmptyStatePanel } from "@/framework/ui/common/EmptyStatePanel";
import { TableSurface } from "@/framework/ui/common/TableSurface";
import taskDetailStyles from "@/modules/data-catalog/components/BuildTaskDetailDrawer.module.css";
import sharedStyles from "@/modules/data-catalog/components/shared.module.css";
import { createResourceSemanticUnderstandingTask, deleteSemanticUnderstandingTask, listResourceSemanticUnderstandingTasks, type CreateSemanticUnderstandingTaskPayload, type SemanticUnderstandingTask } from "@/modules/data-catalog/services/semantic-understanding-task.service";
import type { CatalogResource } from "@/modules/data-catalog/types/data-catalog";

import styles from "./ResourceSemanticUnderstandingPanel.module.css";

function formatTime(value: number) { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "medium", hour12: false }).format(value < 100_000_000_000 ? value * 1000 : value) : "-"; }

export function ResourceSemanticUnderstandingPanel({ active, resource }: { active: boolean; resource: CatalogResource }) {
  const { t } = useTranslation(); const { message, modal } = useAppServices(); const [form] = Form.useForm<CreateSemanticUnderstandingTaskPayload>();
  const [tasks, setTasks] = useState<SemanticUnderstandingTask[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [open, setOpen] = useState(false); const [creating, setCreating] = useState(false);
  const [detailTask, setDetailTask] = useState<SemanticUnderstandingTask | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setTasks(await listResourceSemanticUnderstandingTasks(resource.id)); } catch (e) { setError(extractRequestErrorMessage(e)); } finally { setLoading(false); } }, [resource.id]);
  useEffect(() => { if (active) void load(); }, [active, load]);
  useEffect(() => { if (!active || !tasks.some((task) => task.status === "pending" || task.status === "running")) return; const timer = window.setInterval(() => void load(), 10_000); return () => window.clearInterval(timer); }, [active, load, tasks]);
  const summary = useMemo(() => tasks.find((task) => task.status === "succeeded" && task.applied) ?? tasks[0], [tasks]);
  const start = async () => { const values = await form.validateFields(); setCreating(true); try { await createResourceSemanticUnderstandingTask({ ...values, resourceId: resource.id }); message.success(t("dataCatalog.semanticWorkspace.started")); setOpen(false); form.resetFields(); await load(); } finally { setCreating(false); } };
  return <div className={styles.root}>
    <section className={styles.summaryCard}><div className={styles.summaryContent}><span className={styles.summaryLabel}>{t("dataCatalog.semanticWorkspace.summary")}</span><strong>{summary?.status === "succeeded" && summary.applied ? t("dataCatalog.semanticWorkspace.applied") : summary?.status === "pending" || summary?.status === "running" ? t("dataCatalog.semanticWorkspace.processing") : t("dataCatalog.semanticWorkspace.notApplied")}</strong></div><Space><AppButton icon={<ReloadOutlined />} onClick={() => void load()}>{t("common.refresh")}</AppButton><AppButton icon={<PlusOutlined />} type="primary" onClick={() => { form.setFieldsValue({ applyMode: "fill_empty", confidenceThreshold: 0.75, includeSampleRows: false }); setOpen(true); }}>{t("dataCatalog.semanticWorkspace.create")}</AppButton></Space></section>
    {error ? <Alert message={error} showIcon type="error" /> : <TableSurface>{!loading && tasks.length === 0 ? <EmptyStatePanel description={t("dataCatalog.semanticWorkspace.empty")} title={t("dataCatalog.semanticWorkspace.empty")} /> : <AppTable columns={[{ dataIndex: "id", title: t("dataCatalog.taskManagement.columns.task"), ellipsis: true }, { dataIndex: "status", title: t("common.status"), render: (value) => <Tag color={value === "failed" ? "error" : value === "succeeded" ? "success" : "processing"}>{t(`dataCatalog.taskManagement.semanticStatus.${value}`)}</Tag> }, { dataIndex: "applyMode", title: t("dataCatalog.taskManagement.columns.applyMode"), render: (value) => t(`dataCatalog.taskManagement.applyMode.${value === "dry_run" ? "dryRun" : value === "fill_empty" ? "fillEmpty" : "force"}`) }, { dataIndex: "confidence", title: t("dataCatalog.taskManagement.columns.confidence"), render: (value) => `${Math.round(value * 100)}%` }, { dataIndex: "applied", title: t("dataCatalog.taskManagement.columns.applied"), render: (value) => <Tag color={value ? "success" : "default"}>{t(value ? "dataCatalog.taskManagement.applied.applied" : "dataCatalog.taskManagement.applied.notApplied")}</Tag> }, { dataIndex: "createTime", title: t("dataCatalog.task.createTime"), render: formatTime }, { key: "actions", title: t("common.actions"), width: 160, fixed: "right", render: (_, task) => <Space className={styles.actionGroup} size={4}><AppButton type="link" onClick={() => setDetailTask(task)}>{t("common.detail")}</AppButton><PermissionGate permissions="catalog:task_manage"><AppButton danger disabled={task.status === "pending" || task.status === "running"} type="link" onClick={() => void modal.confirm({ title: t("dataCatalog.taskManagement.semantic.deleteTitle"), content: t("dataCatalog.taskManagement.semantic.deleteDescription", { id: task.id }), okButtonProps: { danger: true }, onOk: async () => { await deleteSemanticUnderstandingTask(task.id); message.success(t("common.success")); await load(); } })}>{t("common.delete")}</AppButton></PermissionGate></Space> }]} dataSource={tasks} loading={loading} pagination={false} rowKey="id" />}</TableSurface>}
    <Modal cancelText={t("common.cancel")} confirmLoading={creating} okText={t("dataCatalog.semanticWorkspace.start")} onCancel={() => setOpen(false)} onOk={() => void start()} open={open} title={t("dataCatalog.semanticWorkspace.createTitle")}><Form form={form} layout="vertical"><Form.Item label={t("dataCatalog.taskManagement.columns.applyMode")} name="applyMode" rules={[{ required: true }]}><Select options={["dry_run", "fill_empty", "force"].map((value) => ({ value, label: t(`dataCatalog.taskManagement.applyMode.${value === "dry_run" ? "dryRun" : value === "fill_empty" ? "fillEmpty" : "force"}`) }))} /></Form.Item><Form.Item label={t("dataCatalog.semanticWorkspace.confidenceThreshold")} name="confidenceThreshold" rules={[{ required: true }]}><InputNumber max={1} min={0} precision={2} style={{ width: "100%" }} step={0.05} /></Form.Item><Form.Item name="includeSampleRows" valuePropName="checked"><Checkbox>{t("dataCatalog.semanticWorkspace.includeSamples")}</Checkbox></Form.Item></Form></Modal>
    {detailTask ? <Drawer className={taskDetailStyles.drawer} destroyOnClose onClose={() => setDetailTask(null)} open styles={{ body: { padding: 16 }, header: { padding: "12px 16px" } }} title={`${t("dataCatalog.task.detail")} · ${detailTask.id}`} width={560}><div className={taskDetailStyles.drawerContent}><section className={taskDetailStyles.sectionCard}><h3 className={taskDetailStyles.sectionTitle}>{t("common.status")}</h3><div className={taskDetailStyles.statusRow}><span className={[sharedStyles.tag, detailTask.status === "failed" ? sharedStyles.taskFailed : detailTask.status === "succeeded" ? sharedStyles.taskSucceeded : sharedStyles.taskRunning].join(" ")}>{t(`dataCatalog.taskManagement.semanticStatus.${detailTask.status}`)}</span></div>{detailTask.failureDetail ? <div className={sharedStyles.calloutWarn}><span className={taskDetailStyles.failureContent}><b>{t("dataCatalog.taskManagement.details.failureReason")}</b><span>{detailTask.failureDetail}</span></span></div> : null}</section><section className={taskDetailStyles.sectionCard}><h3 className={taskDetailStyles.sectionTitle}>{t("dataCatalog.taskManagement.details.taskInformation")}</h3><Descriptions bordered className={taskDetailStyles.descriptionBlock} column={1} size="small"><Descriptions.Item label={t("dataCatalog.taskManagement.columns.scope")}>{t("dataCatalog.taskManagement.scope.resource")}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.build.resource")}>{resource.name}</Descriptions.Item><Descriptions.Item label={t("common.status")}>{t(`dataCatalog.taskManagement.semanticStatus.${detailTask.status}`)}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.taskManagement.columns.applyMode")}>{t(`dataCatalog.taskManagement.applyMode.${detailTask.applyMode === "dry_run" ? "dryRun" : detailTask.applyMode === "fill_empty" ? "fillEmpty" : "force"}`)}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.taskManagement.columns.confidence")}>{`${Math.round(detailTask.confidence * 100)}%`}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.taskManagement.columns.applied")}>{t(detailTask.applied ? "dataCatalog.taskManagement.applied.applied" : "dataCatalog.taskManagement.applied.notApplied")}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.taskManagement.details.agentId")}>{detailTask.agentId || "-"}</Descriptions.Item><Descriptions.Item label={t("dataCatalog.task.createTime")}>{formatTime(detailTask.createTime)}</Descriptions.Item></Descriptions></section></div></Drawer> : null}
  </div>;
}
