
### 解析SSE-amap-sse-server
POST https://127.0.0.1//api/agent-operator-integration/v1/mcp/parse/sse
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>

{
  "mode": "sse",
  "url": "https://mcp.amap.com/sse?key=4402d421c6333f99f01e751816590472"
}


### 注册MCP服务，sse模式 , remote mcp server
POST http://localhost:9000/api/agent-operator-integration/v1/mcp/manage/register
Content-Type: application/json
Authorization: Bearer <ACCESS_TOKEN>

{
  "name": "amap-sse-server-test",
  "description": "这是高德地图sse mcp server",
  "mode": "sse",
  "url": "https://mcp.amap.com/sse?key=4402d421c6333f99f01e751816590472",
  "headers": {
    "Content-Type": "application/json",
    "Authorization": "Bearer 1234567890",
    "X-Custom-Header": "custom-value"
  },
  "source": "custom",
  "category": "test"
}


### 调用MCP工具 - amap-sse-server
POST http://127.0.0.1:9000/api/agent-operator-integration/internal-v1/mcp/proxy/tool/call
Content-Type: application/json

{
  "mcp_id": "c7a12c4a-c5e9-4e91-95f0-db25c27e23ee",
  "tool_name": "maps_text_search",
  "parameters": {
      "city": "上海",
      "keywords": "爱数大厦",
      "citylimit": true
  }
}