export const executionFactoryModuleManifest = {
  id: "execution-factory",
  name: "Execution Factory",
  permissions: [
    "execution-factory:operator:view",
    "execution-factory:operator:create",
    "execution-factory:operator:edit",
    "execution-factory:operator:publish",
    "execution-factory:operator:delete",
    "execution-factory:operator:debug",
    "execution-factory:toolbox:view",
    "execution-factory:toolbox:create",
    "execution-factory:toolbox:edit",
    "execution-factory:toolbox:publish",
    "execution-factory:toolbox:delete",
    "execution-factory:tool:view",
    "execution-factory:tool:create",
    "execution-factory:tool:edit",
    "execution-factory:tool:delete",
    "execution-factory:tool:debug",
    "execution-factory:catalog:view",
    "execution-factory:catalog:install",
    "execution-factory:impex:export",
    "execution-factory:impex:import",
    "execution-factory:mcp:view",
    "execution-factory:mcp:create",
    "execution-factory:mcp:edit",
    "execution-factory:mcp:publish",
    "execution-factory:mcp:delete",
    "execution-factory:mcp:debug",
    "execution-factory:skill:view",
    "execution-factory:skill:create",
    "execution-factory:skill:edit",
    "execution-factory:skill:publish",
    "execution-factory:skill:delete",
  ],
  requiresShell: true,
  supportsEmbedded: false,
  supportsReadOnly: false,
  services: [
    "agent-operator-integration/operator",
    "agent-operator-integration/tool-box",
    "agent-operator-integration/mcp",
    "agent-operator-integration/skill",
    "agent-operator-integration/impex",
  ],
  scenes: [
    {
      id: "execution-factory.unit-management",
      exportName: "UnitManagementListScene",
      description: "Manage registered execution operators and toolboxes.",
      inputs: ["defaultKeyword?", "onOpenDetail?"],
    },
    {
      id: "execution-factory.unit-form",
      exportName: "UnitFormScene",
      description: "Create or edit execution operators.",
      inputs: ["mode", "operatorId?", "onBack?", "onSubmitSuccess?"],
    },
    {
      id: "execution-factory.toolbox-form",
      exportName: "ToolboxFormScene",
      description: "Create or edit execution toolboxes.",
      inputs: ["mode", "boxId?", "onBack?", "onSubmitSuccess?"],
    },
    {
      id: "execution-factory.toolbox-tools",
      exportName: "ToolboxToolsScene",
      description: "Manage tools inside a toolbox.",
      inputs: ["boxId", "onBack?"],
    },
    {
      id: "execution-factory.mcp-detail",
      exportName: "McpDetailScene",
      description: "View MCP tools, schemas, and debug.",
      inputs: ["mcpId", "onBack?"],
    },
    {
      id: "execution-factory.skill-detail",
      exportName: "SkillDetailScene",
      description: "View skill content and package files.",
      inputs: ["skillId", "onBack?"],
    },
    {
      id: "execution-factory.catalog",
      exportName: "CatalogListScene",
      description: "Browse operator and toolbox market entries for installable execution units.",
      inputs: ["defaultKeyword?", "onOpenDetail?"],
    },
    {
      id: "execution-factory.mcp-list",
      exportName: "McpListScene",
      description: "Manage MCP server configurations.",
      inputs: [],
    },
    {
      id: "execution-factory.mcp-form",
      exportName: "McpFormScene",
      description: "Register a new MCP server.",
      inputs: ["onBack?", "onSubmitSuccess?"],
    },
    {
      id: "execution-factory.skill-list",
      exportName: "SkillListScene",
      description: "Manage Agent Skills.",
      inputs: [],
    },
    {
      id: "execution-factory.skill-form",
      exportName: "SkillFormScene",
      description: "Register Agent Skills from zip or content.",
      inputs: ["onBack?", "onSubmitSuccess?"],
    },
    {
      id: "execution-factory.skill-edit",
      exportName: "SkillEditScene",
      description: "Edit skill metadata and package content.",
      inputs: ["skillId?", "onBack?", "onSubmitSuccess?"],
    },
  ],
} as const;
