/**
 * Copyright (c) 2026 OpenBKN
 * SPDX-License-Identifier: LicenseRef-OpenBKN
 * Licensed under the OpenBKN License, a modified Apache 2.0 with Additional
 * Conditions. See LICENSE for the full text.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const postMock = vi.hoisted(() => vi.fn());
const getMock = vi.hoisted(() => vi.fn());
const putMock = vi.hoisted(() => vi.fn());

vi.mock("@/framework/request/http", () => ({
  http: { get: getMock, post: postMock, put: putMock },
}));

describe("resource.service · previewCatalogResource", () => {
  beforeEach(() => {
    vi.resetModules();
    vi.stubEnv("VITE_USE_MOCK", "false");
    getMock.mockReset();
    postMock.mockReset();
    putMock.mockReset();
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("uses Vega paging and the GET method override", async () => {
    postMock.mockResolvedValue({ data: { entries: [{ id: "r-1" }], total_count: 42 } });
    const { previewCatalogResource } = await import(
      "@/modules/data-catalog/services/resource.service"
    );
    const { transformPrecisionSafeJSONResponse } = await import(
      "@/framework/request/precision-safe-json"
    );

    const result = await previewCatalogResource("r-1", { limit: 10, offset: 20 });

    expect(postMock).toHaveBeenCalledWith(
      "/vega-backend/v1/resources/r-1/data",
      {
        need_total: true,
        paging: { limit: 10, mode: "single", offset: 20 },
      },
      {
        headers: { "X-HTTP-Method-Override": "GET" },
        transformResponse: transformPrecisionSafeJSONResponse,
      },
    );
    expect(result).toEqual({ rows: [{ id: "r-1" }], total: 42 });
  });
});

describe("resource.service · listCatalogResourcePage", () => {
  beforeEach(() => {
    vi.resetModules();
    vi.stubEnv("VITE_USE_MOCK", "false");
    getMock.mockReset();
    putMock.mockReset();
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("sends schema to the server so totals and pages are filtered consistently", async () => {
    getMock.mockResolvedValue({
      data: {
        entries: [
          {
            catalog_id: "cat-1",
            category: "table",
            id: "res-1",
            last_discover_status: "error",
            index_name: "bkn_res-1",
            local_status: "available",
            name: "orders",
            schema: "external_data",
            status: "stale",
            status_message: "discover metadata failed",
            update_time: 123,
          },
        ],
        total_count: 21,
      },
    });
    const { listCatalogResourcePage } = await import(
      "@/modules/data-catalog/services/resource.service"
    );

    const result = await listCatalogResourcePage({
      catalogId: "cat-1",
      limit: 10,
      offset: 10,
      schema: "external_data",
    });

    expect(getMock).toHaveBeenCalledWith("/vega-backend/v1/resources", {
      params: {
        catalog_id: "cat-1",
        category: undefined,
        limit: 10,
        name: undefined,
        offset: 10,
        schema: "external_data",
      },
    });
    expect(result).toEqual({
      items: [expect.objectContaining({
        columnCount: null,
        id: "res-1",
        expectedUpdateTime: 123,
        lastDiscoverStatus: "error",
        localIndexName: "bkn_res-1",
        localIndexStatus: "available",
        schemaName: "external_data",
        status: "stale",
        statusMessage: "discover metadata failed",
      })],
      total: 21,
    });
    expect(result.items[0]?.updateTime).not.toBe("");
  });
});

describe("resource.service · updateCatalogResource", () => {
  beforeEach(() => {
    vi.resetModules();
    vi.stubEnv("VITE_USE_MOCK", "false");
    getMock.mockReset();
    putMock.mockReset();
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("removes self-referencing feature properties while preserving cross-field references", async () => {
    putMock.mockResolvedValue({});
    getMock.mockResolvedValue({
      data: {
        catalog_id: "cat-1",
        category: "table",
        id: "res-1",
        name: "orders",
        schema_definition: [],
      },
    });
    const { updateCatalogResource } = await import(
      "@/modules/data-catalog/services/resource.service"
    );

    await updateCatalogResource("res-1", {
      catalogId: "cat-1",
      category: "table",
      description: "",
      expectedUpdateTime: 123,
      name: "orders",
      schema: [
        {
          description: "Request identifier generated by semantic understanding",
          displayName: "Request number",
          name: "request_no",
          type: "string",
          features: [
            {
              name: "fulltext",
              featureType: "fulltext",
              refProperty: "request_no",
              isNative: true,
            },
            {
              name: "linked_keyword",
              featureType: "keyword",
              refProperty: "external_keyword",
            },
          ],
        },
      ],
      sourceIdentifier: "orders",
    });

    expect(putMock).toHaveBeenCalledWith("/vega-backend/v1/resources/res-1", {
      catalog_id: "cat-1",
      category: "table",
      description: "",
      expected_update_time: 123,
      name: "orders",
      schema_definition: [
        expect.objectContaining({
          description: "Request identifier generated by semantic understanding",
          display_name: "Request number",
          features: [
            expect.not.objectContaining({ ref_property: "request_no" }),
            expect.objectContaining({ ref_property: "external_keyword" }),
          ],
        }),
      ],
      index_config: undefined,
      source_identifier: "orders",
    });
  });
});

describe("resource.service · mock update boundaries", () => {
  beforeEach(() => {
    vi.resetModules();
    vi.stubEnv("VITE_USE_MOCK", "true");
  });

  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("returns an HTTP-shaped 404 for a missing resource", async () => {
    const { updateCatalogResource } = await import(
      "@/modules/data-catalog/services/resource.service"
    );

    await expect(
      updateCatalogResource("missing-resource", {
        catalogId: "cat-001",
        category: "table",
        description: "",
        expectedUpdateTime: 1,
        name: "missing",
        schema: [],
        sourceIdentifier: "missing",
      }),
    ).rejects.toMatchObject({
      response: {
        data: { error_code: "VegaBackend.Resource.NotFound" },
        status: 404,
        statusText: "Not Found",
      },
    });
  });

  it("rejects a stale resource version without changing the resource", async () => {
    const { getCatalogResource, updateCatalogResource } = await import(
      "@/modules/data-catalog/services/resource.service"
    );
    const current = await getCatalogResource("res-orders");
    expect(current).not.toBeNull();
    if (!current) {
      return;
    }

    await expect(
      updateCatalogResource(current.id, {
        ...current,
        expectedUpdateTime: 0,
      }),
    ).rejects.toMatchObject({
      response: {
        data: { error_code: "VegaBackend.InvalidParameter.RequestBody" },
        status: 400,
      },
    });

    await expect(
      updateCatalogResource(current.id, {
        ...current,
        description: "stale update",
        expectedUpdateTime: current.expectedUpdateTime - 1,
      }),
    ).rejects.toMatchObject({ response: { status: 409 } });
    await expect(getCatalogResource(current.id)).resolves.toMatchObject({
      description: current.description,
      expectedUpdateTime: current.expectedUpdateTime,
    });
  });

  it("checks catalog and category while ignoring source identifier", async () => {
    const { getCatalogResource, updateCatalogResource } = await import(
      "@/modules/data-catalog/services/resource.service"
    );
    const current = await getCatalogResource("res-orders");
    expect(current).not.toBeNull();
    if (!current) {
      return;
    }

    await expect(
      updateCatalogResource(current.id, {
        ...current,
        catalogId: "another-catalog",
      }),
    ).rejects.toMatchObject({ response: { status: 400 } });
    await expect(
      updateCatalogResource(current.id, {
        ...current,
        category: "dataset",
      }),
    ).rejects.toMatchObject({ response: { status: 400 } });

    const updated = await updateCatalogResource(current.id, {
      ...current,
      description: "updated description",
      sourceIdentifier: "ignored.source",
    });
    expect(updated).toMatchObject({
      description: "updated description",
      sourceIdentifier: current.sourceIdentifier,
    });
  });
});
